### ISSUE TITLE
UI Docs: Issue in props of table-pagination

### ISSUE THREAD

**Issue by pranavp10** [medusajs/ui#92]
The table header and pagination are not affixed in place; instead, the header should remain at the top, the pagination at the bottom, and the body should be scrollable.

**Comment by kasperkristensen** [comment]
Hi @pranavp10, the components in this library are primitives, and don't enforce a particular layout. You can easily implement this yourself by applying `sticky` to the table header, and overflow-{x|y}-auto to the table itself. It's not something we are going to have as default styles.
